### ISSUE TITLE
Issue with gen_mixed_code

### ISSUE THREAD

**Issue by mbledkowski** [iscc/iscc-core#127]
Hello,
When I try to encode both audio and video codes into a single code, I get the following error:
```console
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/mble/Code/repos/mbledkowski/mdrnshData/iscc-api/main.py", line 16, in iscc
    return ic.gen_mixed_code(
           ^^^^^^^^^^^^^^^^^^
  File "/home/mble/.cache/pypoetry/virtualenvs/iscc-api-5CADumn--py3.12/lib64/python3.12/site-packages/iscc_core/code_content_mixed.py", line 36, in gen_mixed_code
    return gen_mixed_code_v0(codes, bits=bits)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/mble/.cache/pypoetry/virtualenvs/iscc-api-5CADumn--py3.12/lib64/python3.12/site-packages/iscc_core/code_content_mixed.py", line 52, in gen_mixed_code_v0
    digests = [ic.decode_base32(ic.iscc_clean(code)) for code in codes]
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/mble/.cache/pypoetry/virtualenvs/iscc-api-5CADumn--py3.12/lib64/python3.12/site-packages/iscc_core/codec.py", line 283, in decode_base32
    return bytes(b32decode(code + "=" * pad_length, casefold=True))
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib64/python3.12/base64.py", line 254, in b32decode
    return _b32decode(_b32alphabet, s, casefold, map01)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib64/python3.12/base64.py", line 240, in _b32decode
    raise binascii.Error('Incorrect padding')
binascii.Error: Incorrect padding
```
Executed code:
```python
            return ic.gen_mixed_code(
                idk.code_audio(fileName).iscc, idk.code_video(fileName).iscc
            )
```

It seems that the issue lies in the decode_base32 function in codec.py, which adds incorrect padding length.

Best regards

**Comment by titusz** [comment]
You had me worried for a moment :). You have to pass the codes wrapped in a sequence. This should work:

```python
ic.gen_mixed_code(
    [idk.code_audio(fileName).iscc, idk.code_video(fileName).iscc]
)
```

**Comment by mbledkowski** [comment]
Your solution works, thank you very much
